### Populate db
POST {{URL}}/trips/populate

### Get all trips
GET {{URL}}/trips
Accept: application/json

### Get all guides
GET {{URL}}/guides
Accept: application/json

### Get a trip by id
GET {{URL}}/trips/1
Accept: application/json

### Add a new trip
POST {{URL}}/trips
Content-Type: application/json

{
  "starttime": "2023-07-01T09:00:00",
  "endtime": "2023-07-01T17:00:00",
  "longitude": 45.0,
  "latitude": -122.0,
  "name": "Beach Adventure",
  "price": 200.0,
  "category": "BEACH",
  "guideId": 1
}

### Update a trip
PUT {{URL}}/trips/1
Content-Type: application/json

{
  "starttime": "2023-07-02T09:00:00",
  "endtime": "2023-07-02T17:00:00",
  "longitude": 45.0,
  "latitude": -122.0,
  "name": "Updated SNOW Adventure",
  "price": 250.0,
  "category": "SNOW",
  "guideId": 1
}

### Delete a trip
DELETE {{URL}}/trips/1

### Add a guide to a trip
PUT {{URL}}/trips/2/guides/2

### Get a trip by id
GET {{URL}}/trips/2
Accept: application/json

### Get all trips in BEACH category
GET {{URL}}/trips/category/BEACH
Accept: application/json

### Get total prices of each guides trip
GET {{URL}}/trips/totalprice
Accept: application/json


